#!/bin/bash

CWD=$(pwd)
cd "$(dirname "$(readlink -f "$0")")"

if [ "$1" = "list" ]; then history/borg list --short repo && exit 0; fi 

if [ ! -d history ]; then
mkdir history
fi

if [ $(rsync -aniHAX bin/ history/bin/ | wc -l) -ne 0 ]; then
	BOOL=true
else
	BOOL=false
fi

rsync -aHAX bin/ history/bin/

if [ ! -L history/borg ]; then
ln -s bin/borg-docker history/borg
fi

if [ ! -L history/src ]; then
ln -s . history/src
fi

CURRENT_VERSION=$(cat history/bin/VERSION)

./history/borg update-binary

NEW_VERSION=$(cat history/bin/VERSION)

if [ "$CURRENT_VERSION" != "$NEW_VERSION" ] || $BOOL; then
	echo "Saving to history"
	rsync -aHAX bin/ history/bin/
	history/borg info repo >/dev/null 2>&1 || history/borg init -e none repo
	history/borg delete repo::"$NEW_VERSION" >/dev/null 2>&1
	history/borg create --chunker-params 10,23,16,4095 repo::"$NEW_VERSION" src/bin src/borg
fi

if [[ $1 =~ ^([0-9]+\.?){3}$ ]]; then

	echo "Requesting specific version from history: $1"
	if [ -d history/extract ]; then trash history/extract; fi
	
	history/borg extract repo::$1  

	if [ $? -ne 0 ]; then
		echo "Only the following versions are available: " 
		history/borg list --short repo
		exit 1 
	fi

	if [ -d "$CWD"/bin ]; then trash "$CWD"/bin ; fi
	
	rsync -aHAX history/extract/ "$CWD"/

	"$CWD"/borg --version

	rm -rf history/extract

else
	
	if [ -f "$CWD"/bin/VERSION ]; then
		echo -n "Upgrading: $(cat "$CWD"/bin/VERSION) to "
	else
		echo -n "Fresh installation: "
	fi
	
	rsync -aHAX history/bin/ "$CWD"/bin/ --delete
	rsync -aHAX history/borg "$CWD"/borg
	
	echo "$(cat "$CWD"/bin/VERSION)"
	
	"$CWD"/borg --version

fi

